project:
  type: website
  output-dir: docs
website:
  title: "Reina Kaino"
  google-analytics: "G-LE1MD5SGQZ"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - text: Blog
        menu: 
          - text: Blog EN
            href: blog/index.qmd
          - text: ブログ JP
            href: blog/index-ja.qmd
      - href: enquiry.qmd
        text: Enquiry
      - href: ja.qmd
        text: 日本語
      - href: portfolio-page.qmd
        text: Portfolio
        
  page-footer:
    left: "© 2025 Reina's Data Studio"
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/reijkg2904/
      - icon: github
        href: https://github.com/reinasdatastudio
      - icon: youtube
        href: https://www.youtube.com/@reinas_data.studio
      - icon: twitter
        href: https://x.com/r_datastudio
    right: "Webpage made with Quarto"
      
format:
  html:
    theme: 
      - Lux
      - site.scss
    title-block-style: plain

editor: visual

resources:
  - blog-footer.html