---
title: "Enquiry"
format: 
  html:
    page-layout: full
---

::::::: enquiry-page
::: enquiry-left
If you have a dataset, question, or project in mind, I’d be happy to hear from you.

You don’t need to have everything figured out — a short description is enough to start the conversation.

I typically respond within **24–48 hours**.

<strong>**Your data and information will be treated confidentially.**</strong>
You are welcome to anonymise or share sample data initially.

##### To help me understand your project, you may include:

-   Your goal or main question
-   Type of dataset (clinical, survey, retail, etc.)
-   Approximate dataset size
-   Timeline or deadline (if any)
-   Whether you can share sample data

You don’t need to provide everything — this just helps me respond more efficiently.
:::

::::: enquiry
<form action="https://formspree.io/f/mdkqleoj" method="POST">

::: name
<label> First Name<br> <input type="text" name="name" required> </label>

<label> Last Name <br><input type="text" name="name" required> </label>
:::

::: name
<label> Email <br><input type="email" name="email" required> </label>

<label> Organisation (Optional)<br><input type="text" name="name"> </label>
:::

<label for="fruits">Type of support needed</label> <select id="fruits" name="fruits"> <option value="apple">Quick fix</option> <option value="banana">Reproducible Analysis</option> <option value="orange">Ongoing Support</option> <option value="grape">Teaching / Mentoring</option><option value="peach">Other (Please specify below)</option> </select>

<label for="message"> Message

```{=html}
<textarea name="message" rows="5" required></textarea>
```

</label>

<button class="button" id="send" type="submit">

Send

</button>

</form>
:::::
:::::::
