---
title: "ggplot便利テクニック"
date: 2026-02-13
description: "ggplot2をわかりやすくまとめました。"
categories: 
  - ggplot2
  - Data Visualisation
format:
  html:
    include-after-body: blog-footer-ja.html
toc: true
draft: true
knitr:
  opts_chunk: 
    dev: "ragg_png"
---

```{r}
library(ggplot2)
library(ggiraph)
```

```{r}
interactive_iris_plot <- iris |>
  dplyr::rename_with(~ gsub(".", " ", .x, fixed = TRUE)) |>
    ggplot(aes(x=`Sepal Length`, y=`Petal Length`)) +
      geom_jitter_interactive(aes(fill = Species,
                                  tooltip = paste0("Sepal Length: ",
                                                  `Sepal Length`,
                                                  "cm",
                                                  "\nPetal Length: ",
                                                  `Petal Length`,
                                                  "cm")),
                              shape = 21,
                              color = "black",
                              size = 2,
                              stroke = 0.8, #border thickness
                              alpha = 0.9,  #transparency
                              ) +
      scale_fill_manual(values = c("setosa" = "pink", 
                                     "versicolor" = "#2A9D8F",
                                     "virginica" = "purple")) +
      coord_fixed(ratio = 1) + #Keeping x and y equal aspect ratio
      scale_x_continuous(labels  = function(x) paste0(x, "cm")) +
      scale_y_continuous(breaks = seq(0, 10, by = 1),labels = function(x) paste0(x, "cm")) +
      labs(title = "Sepal Length vs Petal Length") +
      theme_minimal(base_size = 12) +
      theme(
        text = element_text(family = "Georgia"),
        plot.title.position = "panel",
      )

girafe(ggobj = interactive_iris_plot)
```

カーソルを合わせれば一つ一つの長さが見れるようになってます。
